### ISSUE TITLE
Linux and windows 3.6 builds

### ISSUE THREAD

**Issue by dmpelt** [conda-forge/edffile-feedstock#5]
It seems like the recent maintenance update ( #4 ) should have created updated builds for python 3.6. On the [anaconda page](https://anaconda.org/conda-forge/edffile/files), however, 3.6 builds are only available for osx. Looking at circle-ci logs, it looks like the new build was skipped because '[ci skip]' was present in the commit message. Is it possible to force a rebuild to create the 3.6 packages for linux and windows?

**Comment by ocefpaf** [comment]
Should be fixed with the noarch package now.
